name: SafeAI CodeGuard Validation
description: Comprehensive validation pipeline for code safety and performance

triggers:
  - push
  - pull_request
  - workflow_dispatch

environment:
  PYTHON_VERSION: "3.9"
  SAFETY_LEVEL: "high"
  REDIS_URL: "redis://localhost:6379"
  MAX_WORKERS: "4"

steps:
  - name: Static Analysis
    command: |
      sacp analyze \
        --level ${SAFETY_LEVEL} \
        --output report.json
    timeout: 1800
    retry: 2
    environment:
      ANALYSIS_MODE: static
  
  - name: Safety Validation
    command: |
      sacp validate \
        --distributed \
        --redis-url ${REDIS_URL} \
        --workers ${MAX_WORKERS}
    timeout: 3600
    retry: 1
    environment:
      VALIDATION_MODE: distributed
  
  - name: Performance Analysis
    command: |
      sacp analyze \
        --mode performance \
        --output perf-report.json
    timeout: 1800
    environment:
      ANALYSIS_MODE: performance
  
  - name: Codebase Indexing
    command: |
      sacp index \
        --exclude "node_modules,.git" \
        --output index.db
    timeout: 1800
    environment:
      INDEX_MODE: full

metadata:
  team: security
  priority: high
  category: validation
